[[plugins]]
package = "/plugins/netlify-plugin-pretty-printing"

[[plugins]]
package = "/plugins/netlify-plugin-build-search-index"

[[plugins]]
package = "/plugins/netlify-plugin-build-crc32"

[[plugins]]
package = "/plugins/netlify-plugin-build-finalize"

[build]
  publish = "public"
  command = "hugo"


[context.production.environment]
  HUGO_VERSION = "0.105.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

# [context.branch-deploy.environment]
#   HUGO_VERSION = "0.81.0"
#
# [context.deploy-preview.environment]
#   HUGO_VERSION = "0.81.0"
